### ISSUE TITLE
defer Q() not printing output.

### ISSUE THREAD

**Issue by adamryman** [y0ssar1an/q#9] opened 2017-03-26 18:51 UTC
```
package main

import (
	. "github.com/y0ssar1an/q"
)

func main() {
	test()
	Q("Third")
}

func test() {
	defer Q("Second")
	Q("First")
}
```

Produces output
```
[18:49:47 qtest/main.go:14 main.test]
0.000s First
0.000s

[18:49:47 qtest/main.go:9 main.main]
0.000s Third
```

Expected
```
[18:49:47 qtest/main.go:14 main.test]
0.000s First
0.000s Second

[18:49:47 qtest/main.go:9 main.main]
0.000s Third
```

**Comment by y0ssar1an** [comment] 2017-04-23 19:26
Thank you for reporting this! I'll look into it immediately.

**Comment by johnSchnake** [comment] 2017-09-14 02:24
Interestingly this works:
```
package main

import (
	. "github.com/y0ssar1an/q"
)

func main() {
	test()
	Q("Third")
}

func test() {
	defer func() {
		Q("Second")
	}()
	Q("First")
}
```
I guess the issue has to do with Q finding itself in the doc and getting the info it should be tryign to print. Maybe because the `ast` isnt considering `Q` to be the function call here, but actually an argument to defer?

**Comment by johnSchnake** [comment] 2017-09-14 02:28
Confirmed when doing adding a 4th one to that. Printing out the caller info that Q is using:
```
func test() {
	defer Q("Third")
	defer func() {
		Q("Second")
	}()
	Q("First")
}
```
```
main.test /Users/johnschnake/go/src/github.com/johnSchnake/qPanic/main.go 17 <nil>
main.test.func1 /Users/johnschnake/go/src/github.com/johnSchnake/qPanic/main.go 15 <nil>
main.test /Users/johnschnake/go/src/github.com/johnSchnake/qPanic/main.go 18 <nil>
main.main /Users/johnschnake/go/src/github.com/johnSchnake/qPanic/main.go 9 <nil>
```
The `Third` one which is the error case is registering at line 18 which (since you cant see it in the comments) is at the very end of the test function. Not at the line where its args can actually get parsed.

**Comment by johnSchnake** [comment] 2017-09-14 03:00
So this issue is not just specific to q apparently. If you do:
```
func test() {
 defer debug.PrintStack()
}
```
You will also get the line for the end of the function, not the line the defer is written on. Will continue to look at this; it is an interesting problem.

**Comment by johnSchnake** [comment] 2017-09-14 03:17
Made https://github.com/golang/go/issues/21877 to pursue the issue. There is a link to an older issue that discussed this but I'm not sure if anything has changed. https://github.com/golang/go/issues/21877

**Comment by johnSchnake** [comment] 2017-09-14 03:18
For the time being, just wrap the call to `Q` in an anonymous function as mentioned above:
```
defer func(){q.Q(...)}
```
and things should be just fine for you

**Comment by johnSchnake** [comment] 2017-09-20 19:40
golang/go#21877 was closed as effectively 'as designed'.  I think this is just a pretty tiny limitation `q.Q` has to deal with. Again, this is a fundamental language limitation which even `debug.PrintStack` and `panic` has to deal with. @y0ssar1an suggest closing this ticket as such and maybe adding a note in the README.

**Comment by y0ssar1an** [comment] 2017-09-20 20:20
@johnSchnake Yeah, it sounds like documenting the issue is the best we can do. Thanks for going down this rabbit hole. We now have a `golang/go` issue we can refer to when explaining why `defer q.Q()` doesn't work.

**Comment by SimonWaldherr** [comment] 2018-10-21 21:52
https://github.com/y0ssar1an/q/pull/26 leads to:
```
[21:49:37 testdata/sample2.go:14 main.test]
0.000s First
0.001s Second

[21:49:37 testdata/sample2.go:9 main.main]
0.001s Third
```

sample2.go contains:
```go
package main

import (
	. ".."
)

func main() {
	test()
	Q("Third")
}

func test() {
	defer Q("Second")
	Q("First")
}
```

**Closed** 2018-11-29 03:49 UTC
Labels: bug
